cask "google-chrome"
cask "iterm2"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "1password"
cask "alfred"

brew "git"
brew "jq"
brew "curl"
brew "mysql-client"
brew "aws-sam-cli"
brew "awscli"
brew "wget"